"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['FaceL.py']
DATA_FILES = ["haarcascade_frontalface_alt.xml","EyeLocatorASEF128x128.fel","Arial Black.ttf","LogoFaceL.png","ColoStateLogo.png"]
OPTIONS = {'argv_emulation': True,
           'iconfile':'FaceLIcon.icns',
           'site_packages':True,
           'plist':dict(
                       CFBundleName               = "FaceL",
                       CFBundleShortVersionString = "1.0.0",     # must be in X.X.X format
                       CFBundleGetInfoString      = "FaceL 1.0.0",
                       CFBundleExecutable         = "FaceL",
                       CFBundleIdentifier         = "net.sourceforge.pyvision",
                   )
           
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
